// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent.dart';
import 'api/auth.dart';
import 'api/guardrails.dart';
import 'api/hardware.dart';
import 'api/send.dart';
import 'api/sign.dart';
import 'api/types.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -889800872;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_deadbolt',
        ioDirectory: 'rust/deadbolt_bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAgentApproveIntent({required String intentId});

  Future<String> crateApiSendBuildUnsignedSendSol({
    required String toAddress,
    required BigInt lamports,
  });

  Future<String> crateApiSendBuildUnsignedSendToken({
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required bool createAtaIfNeeded,
  });

  Future<void> crateApiAuthChangeAppPassword({
    required String current,
    required String newPassword,
  });

  String? crateApiGuardrailsCheckManualTransaction({
    String? mint,
    String? outputMint,
  });

  Future<void> crateApiWalletCompleteOnboarding();

  Future<WalletInfoDto> crateApiHardwareConnectHardwareWallet({
    required String portPath,
    required String name,
  });

  Future<String> crateApiAgentCreateApiKey({required String label});

  Future<CreateWalletResult> crateApiWalletCreateWallet({
    required String name,
    required int wordCount,
  });

  String? crateApiWalletGetActiveWallet();

  Future<String> crateApiAgentGetFullApiKey({required String tokenPrefix});

  GuardrailsConfigDto crateApiGuardrailsGetGuardrailsConfig();

  String crateApiWalletGetHeliusApiKey();

  Future<List<String>> crateApiWalletGetMnemonic({required String address});

  String crateApiWalletGetNetwork();

  bool crateApiAuthHasAppPassword();

  Future<WalletInfoDto> crateApiWalletImportWallet({
    required String name,
    required List<String> words,
  });

  Future<void> crateApiInitInitApp();

  bool crateApiAgentIsAgentServerRunning();

  bool crateApiAuthIsAppLocked();

  bool crateApiWalletIsWalletUnlocked({required String address});

  List<ApiKeyEntry> crateApiAgentListApiKeys();

  Future<List<WalletInfoDto>> crateApiWalletListWallets();

  Future<void> crateApiWalletLockAllWallets();

  Future<void> crateApiAuthLockApp();

  Future<void> crateApiWalletLockWallet({required String address});

  bool crateApiWalletNeedsOnboarding();

  List<String> crateApiWalletRandomBip39Words({required int count});

  Future<void> crateApiAgentRejectIntent({required String intentId});

  Future<void> crateApiWalletRemoveWallet({required String address});

  Future<void> crateApiWalletResetOnboarding();

  Future<void> crateApiAgentRevokeApiKey({required String token});

  Future<List<DetectedPortDto>> crateApiHardwareScanHardwareWallets();

  Future<void> crateApiWalletSetActiveWallet({required String address});

  Future<void> crateApiAuthSetAppPassword({required String password});

  Future<void> crateApiWalletSetHeliusApiKey({required String key});

  Future<void> crateApiWalletSetNetwork({required String network});

  Future<SignedTxDto> crateApiSignSignMessage({required String messageHex});

  Future<SignedTxDto> crateApiSendSignSendSol({
    required String toAddress,
    required BigInt lamports,
    required String recentBlockhash,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  });

  Future<SignedTxDto> crateApiSendSignSendSolHardware({
    required String portPath,
    required String toAddress,
    required BigInt lamports,
    required String recentBlockhash,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  });

  Future<SignedTxDto> crateApiSendSignSendToken({
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required String recentBlockhash,
    required bool createAtaIfNeeded,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  });

  Future<SignedTxDto> crateApiSendSignSendTokenHardware({
    required String portPath,
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required String recentBlockhash,
    required bool createAtaIfNeeded,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  });

  Future<SignedTxDto> crateApiSignSignSerializedTransaction({
    required String unsignedTxBase64,
  });

  Future<SignedTxDto> crateApiSignSignSerializedTransactionHardware({
    required String portPath,
    required String unsignedTxBase64,
  });

  Future<AgentStatusEvent> crateApiAgentStartAgentServer({required int port});

  void crateApiAgentStopAgentServer();

  Stream<IntentEvent> crateApiAgentStreamIntents();

  Future<void> crateApiAuthUnlockApp();

  Future<void> crateApiWalletUnlockWallet({required String address});

  Future<void> crateApiAgentUpdateAgentWalletData({
    double? solBalance,
    double? solUsd,
    required String tokensJson,
    required String historyJson,
    required String pricesJson,
  });

  Future<void> crateApiGuardrailsUpdateGuardrailsConfig({
    required GuardrailsConfigDto dto,
  });

  Future<void> crateApiAgentUpdateIntentStatus({
    required String intentId,
    required String status,
    String? signature,
    String? error,
  });

  bool crateApiWalletValidateMnemonic({required List<String> words});

  Future<void> crateApiAuthVerifyAppPassword({required String password});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAgentApproveIntent({required String intentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentApproveIntentConstMeta,
        argValues: [intentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentApproveIntentConstMeta =>
      const TaskConstMeta(debugName: "approve_intent", argNames: ["intentId"]);

  @override
  Future<String> crateApiSendBuildUnsignedSendSol({
    required String toAddress,
    required BigInt lamports,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toAddress, serializer);
          sse_encode_u_64(lamports, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendBuildUnsignedSendSolConstMeta,
        argValues: [toAddress, lamports],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendBuildUnsignedSendSolConstMeta =>
      const TaskConstMeta(
        debugName: "build_unsigned_send_sol",
        argNames: ["toAddress", "lamports"],
      );

  @override
  Future<String> crateApiSendBuildUnsignedSendToken({
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required bool createAtaIfNeeded,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toAddress, serializer);
          sse_encode_String(mintAddress, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_bool(createAtaIfNeeded, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendBuildUnsignedSendTokenConstMeta,
        argValues: [toAddress, mintAddress, amount, createAtaIfNeeded],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendBuildUnsignedSendTokenConstMeta =>
      const TaskConstMeta(
        debugName: "build_unsigned_send_token",
        argNames: ["toAddress", "mintAddress", "amount", "createAtaIfNeeded"],
      );

  @override
  Future<void> crateApiAuthChangeAppPassword({
    required String current,
    required String newPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(current, serializer);
          sse_encode_String(newPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthChangeAppPasswordConstMeta,
        argValues: [current, newPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthChangeAppPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "change_app_password",
        argNames: ["current", "newPassword"],
      );

  @override
  String? crateApiGuardrailsCheckManualTransaction({
    String? mint,
    String? outputMint,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(mint, serializer);
          sse_encode_opt_String(outputMint, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGuardrailsCheckManualTransactionConstMeta,
        argValues: [mint, outputMint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGuardrailsCheckManualTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "check_manual_transaction",
        argNames: ["mint", "outputMint"],
      );

  @override
  Future<void> crateApiWalletCompleteOnboarding() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCompleteOnboardingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCompleteOnboardingConstMeta =>
      const TaskConstMeta(debugName: "complete_onboarding", argNames: []);

  @override
  Future<WalletInfoDto> crateApiHardwareConnectHardwareWallet({
    required String portPath,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(portPath, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_info_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHardwareConnectHardwareWalletConstMeta,
        argValues: [portPath, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHardwareConnectHardwareWalletConstMeta =>
      const TaskConstMeta(
        debugName: "connect_hardware_wallet",
        argNames: ["portPath", "name"],
      );

  @override
  Future<String> crateApiAgentCreateApiKey({required String label}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentCreateApiKeyConstMeta,
        argValues: [label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentCreateApiKeyConstMeta =>
      const TaskConstMeta(debugName: "create_api_key", argNames: ["label"]);

  @override
  Future<CreateWalletResult> crateApiWalletCreateWallet({
    required String name,
    required int wordCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_u_32(wordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_create_wallet_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCreateWalletConstMeta,
        argValues: [name, wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCreateWalletConstMeta => const TaskConstMeta(
    debugName: "create_wallet",
    argNames: ["name", "wordCount"],
  );

  @override
  String? crateApiWalletGetActiveWallet() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetActiveWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetActiveWalletConstMeta =>
      const TaskConstMeta(debugName: "get_active_wallet", argNames: []);

  @override
  Future<String> crateApiAgentGetFullApiKey({required String tokenPrefix}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tokenPrefix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentGetFullApiKeyConstMeta,
        argValues: [tokenPrefix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentGetFullApiKeyConstMeta => const TaskConstMeta(
    debugName: "get_full_api_key",
    argNames: ["tokenPrefix"],
  );

  @override
  GuardrailsConfigDto crateApiGuardrailsGetGuardrailsConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_guardrails_config_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGuardrailsGetGuardrailsConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGuardrailsGetGuardrailsConfigConstMeta =>
      const TaskConstMeta(debugName: "get_guardrails_config", argNames: []);

  @override
  String crateApiWalletGetHeliusApiKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetHeliusApiKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetHeliusApiKeyConstMeta =>
      const TaskConstMeta(debugName: "get_helius_api_key", argNames: []);

  @override
  Future<List<String>> crateApiWalletGetMnemonic({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetMnemonicConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetMnemonicConstMeta =>
      const TaskConstMeta(debugName: "get_mnemonic", argNames: ["address"]);

  @override
  String crateApiWalletGetNetwork() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetNetworkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetNetworkConstMeta =>
      const TaskConstMeta(debugName: "get_network", argNames: []);

  @override
  bool crateApiAuthHasAppPassword() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthHasAppPasswordConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthHasAppPasswordConstMeta =>
      const TaskConstMeta(debugName: "has_app_password", argNames: []);

  @override
  Future<WalletInfoDto> crateApiWalletImportWallet({
    required String name,
    required List<String> words,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_list_String(words, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_info_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletImportWalletConstMeta,
        argValues: [name, words],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletImportWalletConstMeta => const TaskConstMeta(
    debugName: "import_wallet",
    argNames: ["name", "words"],
  );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiAgentIsAgentServerRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentIsAgentServerRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentIsAgentServerRunningConstMeta =>
      const TaskConstMeta(debugName: "is_agent_server_running", argNames: []);

  @override
  bool crateApiAuthIsAppLocked() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthIsAppLockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthIsAppLockedConstMeta =>
      const TaskConstMeta(debugName: "is_app_locked", argNames: []);

  @override
  bool crateApiWalletIsWalletUnlocked({required String address}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletIsWalletUnlockedConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletIsWalletUnlockedConstMeta =>
      const TaskConstMeta(
        debugName: "is_wallet_unlocked",
        argNames: ["address"],
      );

  @override
  List<ApiKeyEntry> crateApiAgentListApiKeys() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_key_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentListApiKeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentListApiKeysConstMeta =>
      const TaskConstMeta(debugName: "list_api_keys", argNames: []);

  @override
  Future<List<WalletInfoDto>> crateApiWalletListWallets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallet_info_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletListWalletsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletListWalletsConstMeta =>
      const TaskConstMeta(debugName: "list_wallets", argNames: []);

  @override
  Future<void> crateApiWalletLockAllWallets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletLockAllWalletsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletLockAllWalletsConstMeta =>
      const TaskConstMeta(debugName: "lock_all_wallets", argNames: []);

  @override
  Future<void> crateApiAuthLockApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthLockAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLockAppConstMeta =>
      const TaskConstMeta(debugName: "lock_app", argNames: []);

  @override
  Future<void> crateApiWalletLockWallet({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletLockWalletConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletLockWalletConstMeta =>
      const TaskConstMeta(debugName: "lock_wallet", argNames: ["address"]);

  @override
  bool crateApiWalletNeedsOnboarding() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletNeedsOnboardingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletNeedsOnboardingConstMeta =>
      const TaskConstMeta(debugName: "needs_onboarding", argNames: []);

  @override
  List<String> crateApiWalletRandomBip39Words({required int count}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(count, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletRandomBip39WordsConstMeta,
        argValues: [count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletRandomBip39WordsConstMeta =>
      const TaskConstMeta(debugName: "random_bip39_words", argNames: ["count"]);

  @override
  Future<void> crateApiAgentRejectIntent({required String intentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentRejectIntentConstMeta,
        argValues: [intentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRejectIntentConstMeta =>
      const TaskConstMeta(debugName: "reject_intent", argNames: ["intentId"]);

  @override
  Future<void> crateApiWalletRemoveWallet({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletRemoveWalletConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletRemoveWalletConstMeta =>
      const TaskConstMeta(debugName: "remove_wallet", argNames: ["address"]);

  @override
  Future<void> crateApiWalletResetOnboarding() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletResetOnboardingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletResetOnboardingConstMeta =>
      const TaskConstMeta(debugName: "reset_onboarding", argNames: []);

  @override
  Future<void> crateApiAgentRevokeApiKey({required String token}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentRevokeApiKeyConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentRevokeApiKeyConstMeta =>
      const TaskConstMeta(debugName: "revoke_api_key", argNames: ["token"]);

  @override
  Future<List<DetectedPortDto>> crateApiHardwareScanHardwareWallets() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_detected_port_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiHardwareScanHardwareWalletsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHardwareScanHardwareWalletsConstMeta =>
      const TaskConstMeta(debugName: "scan_hardware_wallets", argNames: []);

  @override
  Future<void> crateApiWalletSetActiveWallet({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletSetActiveWalletConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSetActiveWalletConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_wallet",
        argNames: ["address"],
      );

  @override
  Future<void> crateApiAuthSetAppPassword({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthSetAppPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthSetAppPasswordConstMeta => const TaskConstMeta(
    debugName: "set_app_password",
    argNames: ["password"],
  );

  @override
  Future<void> crateApiWalletSetHeliusApiKey({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletSetHeliusApiKeyConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSetHeliusApiKeyConstMeta =>
      const TaskConstMeta(debugName: "set_helius_api_key", argNames: ["key"]);

  @override
  Future<void> crateApiWalletSetNetwork({required String network}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletSetNetworkConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSetNetworkConstMeta =>
      const TaskConstMeta(debugName: "set_network", argNames: ["network"]);

  @override
  Future<SignedTxDto> crateApiSignSignMessage({required String messageHex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignSignMessageConstMeta,
        argValues: [messageHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignSignMessageConstMeta =>
      const TaskConstMeta(debugName: "sign_message", argNames: ["messageHex"]);

  @override
  Future<SignedTxDto> crateApiSendSignSendSol({
    required String toAddress,
    required BigInt lamports,
    required String recentBlockhash,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toAddress, serializer);
          sse_encode_u_64(lamports, serializer);
          sse_encode_String(recentBlockhash, serializer);
          sse_encode_opt_box_autoadd_u_32(computeUnitLimit, serializer);
          sse_encode_opt_box_autoadd_u_64(computeUnitPrice, serializer);
          sse_encode_opt_box_autoadd_u_64(jitoTipLamports, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendSignSendSolConstMeta,
        argValues: [
          toAddress,
          lamports,
          recentBlockhash,
          computeUnitLimit,
          computeUnitPrice,
          jitoTipLamports,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSignSendSolConstMeta => const TaskConstMeta(
    debugName: "sign_send_sol",
    argNames: [
      "toAddress",
      "lamports",
      "recentBlockhash",
      "computeUnitLimit",
      "computeUnitPrice",
      "jitoTipLamports",
    ],
  );

  @override
  Future<SignedTxDto> crateApiSendSignSendSolHardware({
    required String portPath,
    required String toAddress,
    required BigInt lamports,
    required String recentBlockhash,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(portPath, serializer);
          sse_encode_String(toAddress, serializer);
          sse_encode_u_64(lamports, serializer);
          sse_encode_String(recentBlockhash, serializer);
          sse_encode_opt_box_autoadd_u_32(computeUnitLimit, serializer);
          sse_encode_opt_box_autoadd_u_64(computeUnitPrice, serializer);
          sse_encode_opt_box_autoadd_u_64(jitoTipLamports, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendSignSendSolHardwareConstMeta,
        argValues: [
          portPath,
          toAddress,
          lamports,
          recentBlockhash,
          computeUnitLimit,
          computeUnitPrice,
          jitoTipLamports,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSignSendSolHardwareConstMeta =>
      const TaskConstMeta(
        debugName: "sign_send_sol_hardware",
        argNames: [
          "portPath",
          "toAddress",
          "lamports",
          "recentBlockhash",
          "computeUnitLimit",
          "computeUnitPrice",
          "jitoTipLamports",
        ],
      );

  @override
  Future<SignedTxDto> crateApiSendSignSendToken({
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required String recentBlockhash,
    required bool createAtaIfNeeded,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(toAddress, serializer);
          sse_encode_String(mintAddress, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_String(recentBlockhash, serializer);
          sse_encode_bool(createAtaIfNeeded, serializer);
          sse_encode_opt_box_autoadd_u_32(computeUnitLimit, serializer);
          sse_encode_opt_box_autoadd_u_64(computeUnitPrice, serializer);
          sse_encode_opt_box_autoadd_u_64(jitoTipLamports, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendSignSendTokenConstMeta,
        argValues: [
          toAddress,
          mintAddress,
          amount,
          recentBlockhash,
          createAtaIfNeeded,
          computeUnitLimit,
          computeUnitPrice,
          jitoTipLamports,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSignSendTokenConstMeta => const TaskConstMeta(
    debugName: "sign_send_token",
    argNames: [
      "toAddress",
      "mintAddress",
      "amount",
      "recentBlockhash",
      "createAtaIfNeeded",
      "computeUnitLimit",
      "computeUnitPrice",
      "jitoTipLamports",
    ],
  );

  @override
  Future<SignedTxDto> crateApiSendSignSendTokenHardware({
    required String portPath,
    required String toAddress,
    required String mintAddress,
    required BigInt amount,
    required String recentBlockhash,
    required bool createAtaIfNeeded,
    int? computeUnitLimit,
    BigInt? computeUnitPrice,
    BigInt? jitoTipLamports,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(portPath, serializer);
          sse_encode_String(toAddress, serializer);
          sse_encode_String(mintAddress, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_String(recentBlockhash, serializer);
          sse_encode_bool(createAtaIfNeeded, serializer);
          sse_encode_opt_box_autoadd_u_32(computeUnitLimit, serializer);
          sse_encode_opt_box_autoadd_u_64(computeUnitPrice, serializer);
          sse_encode_opt_box_autoadd_u_64(jitoTipLamports, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendSignSendTokenHardwareConstMeta,
        argValues: [
          portPath,
          toAddress,
          mintAddress,
          amount,
          recentBlockhash,
          createAtaIfNeeded,
          computeUnitLimit,
          computeUnitPrice,
          jitoTipLamports,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendSignSendTokenHardwareConstMeta =>
      const TaskConstMeta(
        debugName: "sign_send_token_hardware",
        argNames: [
          "portPath",
          "toAddress",
          "mintAddress",
          "amount",
          "recentBlockhash",
          "createAtaIfNeeded",
          "computeUnitLimit",
          "computeUnitPrice",
          "jitoTipLamports",
        ],
      );

  @override
  Future<SignedTxDto> crateApiSignSignSerializedTransaction({
    required String unsignedTxBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(unsignedTxBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignSignSerializedTransactionConstMeta,
        argValues: [unsignedTxBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignSignSerializedTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "sign_serialized_transaction",
        argNames: ["unsignedTxBase64"],
      );

  @override
  Future<SignedTxDto> crateApiSignSignSerializedTransactionHardware({
    required String portPath,
    required String unsignedTxBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(portPath, serializer);
          sse_encode_String(unsignedTxBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_signed_tx_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignSignSerializedTransactionHardwareConstMeta,
        argValues: [portPath, unsignedTxBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignSignSerializedTransactionHardwareConstMeta =>
      const TaskConstMeta(
        debugName: "sign_serialized_transaction_hardware",
        argNames: ["portPath", "unsignedTxBase64"],
      );

  @override
  Future<AgentStatusEvent> crateApiAgentStartAgentServer({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_status_event,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentStartAgentServerConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentStartAgentServerConstMeta =>
      const TaskConstMeta(debugName: "start_agent_server", argNames: ["port"]);

  @override
  void crateApiAgentStopAgentServer() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAgentStopAgentServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentStopAgentServerConstMeta =>
      const TaskConstMeta(debugName: "stop_agent_server", argNames: []);

  @override
  Stream<IntentEvent> crateApiAgentStreamIntents() {
    final sink = RustStreamSink<IntentEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_intent_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 47,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiAgentStreamIntentsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentStreamIntentsConstMeta =>
      const TaskConstMeta(debugName: "stream_intents", argNames: ["sink"]);

  @override
  Future<void> crateApiAuthUnlockApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthUnlockAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthUnlockAppConstMeta =>
      const TaskConstMeta(debugName: "unlock_app", argNames: []);

  @override
  Future<void> crateApiWalletUnlockWallet({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletUnlockWalletConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletUnlockWalletConstMeta =>
      const TaskConstMeta(debugName: "unlock_wallet", argNames: ["address"]);

  @override
  Future<void> crateApiAgentUpdateAgentWalletData({
    double? solBalance,
    double? solUsd,
    required String tokensJson,
    required String historyJson,
    required String pricesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_f_64(solBalance, serializer);
          sse_encode_opt_box_autoadd_f_64(solUsd, serializer);
          sse_encode_String(tokensJson, serializer);
          sse_encode_String(historyJson, serializer);
          sse_encode_String(pricesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentUpdateAgentWalletDataConstMeta,
        argValues: [solBalance, solUsd, tokensJson, historyJson, pricesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentUpdateAgentWalletDataConstMeta =>
      const TaskConstMeta(
        debugName: "update_agent_wallet_data",
        argNames: [
          "solBalance",
          "solUsd",
          "tokensJson",
          "historyJson",
          "pricesJson",
        ],
      );

  @override
  Future<void> crateApiGuardrailsUpdateGuardrailsConfig({
    required GuardrailsConfigDto dto,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_guardrails_config_dto(dto, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGuardrailsUpdateGuardrailsConfigConstMeta,
        argValues: [dto],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGuardrailsUpdateGuardrailsConfigConstMeta =>
      const TaskConstMeta(
        debugName: "update_guardrails_config",
        argNames: ["dto"],
      );

  @override
  Future<void> crateApiAgentUpdateIntentStatus({
    required String intentId,
    required String status,
    String? signature,
    String? error,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intentId, serializer);
          sse_encode_String(status, serializer);
          sse_encode_opt_String(signature, serializer);
          sse_encode_opt_String(error, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAgentUpdateIntentStatusConstMeta,
        argValues: [intentId, status, signature, error],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentUpdateIntentStatusConstMeta =>
      const TaskConstMeta(
        debugName: "update_intent_status",
        argNames: ["intentId", "status", "signature", "error"],
      );

  @override
  bool crateApiWalletValidateMnemonic({required List<String> words}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(words, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 53)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletValidateMnemonicConstMeta,
        argValues: [words],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletValidateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "validate_mnemonic", argNames: ["words"]);

  @override
  Future<void> crateApiAuthVerifyAppPassword({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthVerifyAppPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthVerifyAppPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "verify_app_password",
        argNames: ["password"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<IntentEvent> dco_decode_StreamSink_intent_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentStatusEvent dco_decode_agent_status_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AgentStatusEvent(
      status: dco_decode_String(arr[0]),
      port: dco_decode_opt_box_autoadd_u_16(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiKeyEntry dco_decode_api_key_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApiKeyEntry(
      tokenMasked: dco_decode_String(arr[0]),
      tokenPrefix: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      createdAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GuardrailsConfigDto dco_decode_box_autoadd_guardrails_config_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_guardrails_config_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CreateWalletResult dco_decode_create_wallet_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CreateWalletResult(
      wallet: dco_decode_wallet_info_dto(arr[0]),
      mnemonicWords: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  DetectedPortDto dco_decode_detected_port_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DetectedPortDto(
      path: dco_decode_String(arr[0]),
      vid: dco_decode_u_16(arr[1]),
      pid: dco_decode_u_16(arr[2]),
      product: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GuardrailsConfigDto dco_decode_guardrails_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GuardrailsConfigDto(
      enabled: dco_decode_bool(arr[0]),
      tokenWhitelist: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IntentEvent dco_decode_intent_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IntentEvent(
      id: dco_decode_String(arr[0]),
      intentTypeJson: dco_decode_String(arr[1]),
      createdAt: dco_decode_u_64(arr[2]),
      apiTokenPrefix: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ApiKeyEntry> dco_decode_list_api_key_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_key_entry).toList();
  }

  @protected
  List<DetectedPortDto> dco_decode_list_detected_port_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_detected_port_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WalletInfoDto> dco_decode_list_wallet_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wallet_info_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SignedTxDto dco_decode_signed_tx_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SignedTxDto(
      base64: dco_decode_String(arr[0]),
      signature: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WalletInfoDto dco_decode_wallet_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WalletInfoDto(
      address: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      source: dco_decode_String(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<IntentEvent> sse_decode_StreamSink_intent_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentStatusEvent sse_decode_agent_status_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_port = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return AgentStatusEvent(
      status: var_status,
      port: var_port,
      error: var_error,
    );
  }

  @protected
  ApiKeyEntry sse_decode_api_key_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tokenMasked = sse_decode_String(deserializer);
    var var_tokenPrefix = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    return ApiKeyEntry(
      tokenMasked: var_tokenMasked,
      tokenPrefix: var_tokenPrefix,
      label: var_label,
      createdAt: var_createdAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  GuardrailsConfigDto sse_decode_box_autoadd_guardrails_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_guardrails_config_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CreateWalletResult sse_decode_create_wallet_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wallet = sse_decode_wallet_info_dto(deserializer);
    var var_mnemonicWords = sse_decode_list_String(deserializer);
    return CreateWalletResult(
      wallet: var_wallet,
      mnemonicWords: var_mnemonicWords,
    );
  }

  @protected
  DetectedPortDto sse_decode_detected_port_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_vid = sse_decode_u_16(deserializer);
    var var_pid = sse_decode_u_16(deserializer);
    var var_product = sse_decode_String(deserializer);
    return DetectedPortDto(
      path: var_path,
      vid: var_vid,
      pid: var_pid,
      product: var_product,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GuardrailsConfigDto sse_decode_guardrails_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_tokenWhitelist = sse_decode_list_String(deserializer);
    return GuardrailsConfigDto(
      enabled: var_enabled,
      tokenWhitelist: var_tokenWhitelist,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IntentEvent sse_decode_intent_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_intentTypeJson = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_apiTokenPrefix = sse_decode_String(deserializer);
    return IntentEvent(
      id: var_id,
      intentTypeJson: var_intentTypeJson,
      createdAt: var_createdAt,
      apiTokenPrefix: var_apiTokenPrefix,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiKeyEntry> sse_decode_list_api_key_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiKeyEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_key_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<DetectedPortDto> sse_decode_list_detected_port_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DetectedPortDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_detected_port_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WalletInfoDto> sse_decode_list_wallet_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WalletInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wallet_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SignedTxDto sse_decode_signed_tx_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_base64 = sse_decode_String(deserializer);
    var var_signature = sse_decode_String(deserializer);
    return SignedTxDto(base64: var_base64, signature: var_signature);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WalletInfoDto sse_decode_wallet_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    return WalletInfoDto(
      address: var_address,
      name: var_name,
      source: var_source,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_intent_event_Sse(
    RustStreamSink<IntentEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_intent_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_status_event(
    AgentStatusEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_opt_box_autoadd_u_16(self.port, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_key_entry(ApiKeyEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tokenMasked, serializer);
    sse_encode_String(self.tokenPrefix, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_opt_box_autoadd_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_guardrails_config_dto(
    GuardrailsConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_guardrails_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_create_wallet_result(
    CreateWalletResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wallet_info_dto(self.wallet, serializer);
    sse_encode_list_String(self.mnemonicWords, serializer);
  }

  @protected
  void sse_encode_detected_port_dto(
    DetectedPortDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_u_16(self.vid, serializer);
    sse_encode_u_16(self.pid, serializer);
    sse_encode_String(self.product, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_guardrails_config_dto(
    GuardrailsConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_list_String(self.tokenWhitelist, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_intent_event(IntentEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.intentTypeJson, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.apiTokenPrefix, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_key_entry(
    List<ApiKeyEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_key_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_detected_port_dto(
    List<DetectedPortDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_detected_port_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_wallet_info_dto(
    List<WalletInfoDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wallet_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_signed_tx_dto(SignedTxDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.base64, serializer);
    sse_encode_String(self.signature, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wallet_info_dto(
    WalletInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.source, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
