import XCTest
import CryptoKit
@testable import DeadboltCore

/// Byte-for-byte compatibility tests against known-good output from @solana/web3.js 1.91.4.
/// Test vectors generated by calypso/generate_test_vectors.js using deterministic inputs.
///
/// Message serialization is tested byte-for-byte (critical for on-chain correctness).
/// Full transaction tests verify message bytes match + signature is valid Ed25519.
/// Note: CryptoKit and tweetnacl produce different (both valid) deterministic Ed25519
/// signatures from the same seed, so we don't compare signature bytes directly.
final class TransactionCompatTests: XCTestCase {

    // Deterministic seed: 32 bytes of 0x01
    private let feePayerSeed = Data(repeating: 0x01, count: 32)
    // The derived public key (from CryptoKit Curve25519, matches web3.js)
    private let feePayerPubkeyHex = "8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c"
    private let recipientHex = "0202020202020202020202020202020202020202020202020202020202020202"
    private let blockhash = "CVDFLCAjXhVWiPXH9nTCTpCgVzmDVoiPzNJYuccr1dqB"

    // MARK: - Helpers

    private func hexToData(_ hex: String) -> Data {
        var data = Data()
        var index = hex.startIndex
        while index < hex.endIndex {
            let nextIndex = hex.index(index, offsetBy: 2)
            let byteString = String(hex[index..<nextIndex])
            if let byte = UInt8(byteString, radix: 16) {
                data.append(byte)
            }
            index = nextIndex
        }
        return data
    }

    private func dataToHex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    private func createTestSigner() throws -> SoftwareSigner {
        let signer = try SoftwareSigner(seed: feePayerSeed)
        XCTAssertEqual(dataToHex(signer.publicKey.data), feePayerPubkeyHex)
        return signer
    }

    /// Verify a signed transaction: message matches expected, signature is valid Ed25519
    private func assertTransactionValid(
        _ tx: Transaction,
        expectedMessageHex: String,
        signer: SoftwareSigner,
        file: StaticString = #file,
        line: UInt = #line
    ) {
        let serialized = tx.serialize()

        // Transaction format: [1 byte sig count] [64 byte sig] [message bytes]
        XCTAssertEqual(serialized[0], 1, "Expected 1 signature", file: file, line: line)

        let signatureBytes = Data(serialized[1..<65])
        let messageBytes = Data(serialized[65...])

        // Message bytes must match web3.js exactly
        XCTAssertEqual(dataToHex(messageBytes), expectedMessageHex,
                       "Message portion of transaction doesn't match web3.js", file: file, line: line)

        // Signature must be valid Ed25519 over the message
        let isValid = SoftwareSigner.verify(
            signature: signatureBytes,
            message: messageBytes,
            publicKey: signer.publicKey
        )
        XCTAssertTrue(isValid, "Signature is not a valid Ed25519 signature", file: file, line: line)
    }

    // MARK: - Vector 1: Simple SOL Transfer (1,000,000 lamports)

    func testVector1_SimpleSOLTransfer_Message() throws {
        let expectedMessageHex = "010001038a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c02020202020202020202020202020202020202020202020202020202020202020000000000000000000000000000000000000000000000000000000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa01020200010c0200000040420f0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000)]
        )

        XCTAssertEqual(dataToHex(message.serialize()), expectedMessageHex,
                       "Message bytes don't match web3.js output")
    }

    func testVector1_SimpleSOLTransfer_FullTx() async throws {
        let expectedMessageHex = "010001038a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c02020202020202020202020202020202020202020202020202020202020202020000000000000000000000000000000000000000000000000000000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa01020200010c0200000040420f0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000)]
        )

        var tx = Transaction(message: message)
        try await tx.sign(with: signer)
        assertTransactionValid(tx, expectedMessageHex: expectedMessageHex, signer: signer)
    }

    // MARK: - Vector 2: SOL Transfer + ComputeBudget (limit 200k, price 50k)

    func testVector2_SOLTransferWithComputeBudget_Message() throws {
        let expectedMessageHex = "010002048a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c020202020202020202020202020202020202020202020202020202020202020200000000000000000000000000000000000000000000000000000000000000000306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a40000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0303000502400d03000300090350c3000000000000020200010c0200000040420f0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [
                ComputeBudgetProgram.setComputeUnitLimit(200_000),
                ComputeBudgetProgram.setComputeUnitPrice(50_000),
                SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000),
            ]
        )

        XCTAssertEqual(dataToHex(message.serialize()), expectedMessageHex,
                       "Message bytes don't match web3.js output")
    }

    func testVector2_SOLTransferWithComputeBudget_FullTx() async throws {
        let expectedMessageHex = "010002048a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c020202020202020202020202020202020202020202020202020202020202020200000000000000000000000000000000000000000000000000000000000000000306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a40000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0303000502400d03000300090350c3000000000000020200010c0200000040420f0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [
                ComputeBudgetProgram.setComputeUnitLimit(200_000),
                ComputeBudgetProgram.setComputeUnitPrice(50_000),
                SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000),
            ]
        )

        var tx = Transaction(message: message)
        try await tx.sign(with: signer)
        assertTransactionValid(tx, expectedMessageHex: expectedMessageHex, signer: signer)
    }

    // MARK: - Vector 3: SOL Transfer + ComputeBudget + Jito Tip (840k lamports)

    func testVector3_SOLTransferWithComputeBudgetAndTip_Message() throws {
        let expectedMessageHex = "010002058a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c020202020202020202020202020202020202020202020202020202020202020278521cb179cebb8589b556a2d5ec94d2498682fdf9bb2af5ad64e491cc4153da00000000000000000000000000000000000000000000000000000000000000000306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a40000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0404000502400d03000400090350c3000000000000030200010c0200000040420f0000000000030200020c0200000040d10c0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))
        let tipAccount = try SolanaPublicKey(base58: "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5")

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [
                ComputeBudgetProgram.setComputeUnitLimit(200_000),
                ComputeBudgetProgram.setComputeUnitPrice(50_000),
                SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000),
                SystemProgram.transfer(from: signer.publicKey, to: tipAccount, lamports: 840_000),
            ]
        )

        XCTAssertEqual(dataToHex(message.serialize()), expectedMessageHex,
                       "Message bytes don't match web3.js output")
    }

    func testVector3_SOLTransferWithComputeBudgetAndTip_FullTx() async throws {
        let expectedMessageHex = "010002058a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c020202020202020202020202020202020202020202020202020202020202020278521cb179cebb8589b556a2d5ec94d2498682fdf9bb2af5ad64e491cc4153da00000000000000000000000000000000000000000000000000000000000000000306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a40000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0404000502400d03000400090350c3000000000000030200010c0200000040420f0000000000030200020c0200000040d10c0000000000"

        let signer = try createTestSigner()
        let recipient = try SolanaPublicKey(data: hexToData(recipientHex))
        let tipAccount = try SolanaPublicKey(base58: "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5")

        let message = try Message(
            feePayer: signer.publicKey,
            recentBlockhash: blockhash,
            instructions: [
                ComputeBudgetProgram.setComputeUnitLimit(200_000),
                ComputeBudgetProgram.setComputeUnitPrice(50_000),
                SystemProgram.transfer(from: signer.publicKey, to: recipient, lamports: 1_000_000),
                SystemProgram.transfer(from: signer.publicKey, to: tipAccount, lamports: 840_000),
            ]
        )

        var tx = Transaction(message: message)
        try await tx.sign(with: signer)
        assertTransactionValid(tx, expectedMessageHex: expectedMessageHex, signer: signer)
    }
}
