// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent_server`, `intent_tx_store`, `mask_token`

/// Start the agent server on port 9876. Async because server binding is async.
/// Returns error if no tokens provided, port is busy, or server already running.
Future<AgentStatusEvent> startAgentServer({required int port}) =>
    RustLib.instance.api.crateApiAgentStartAgentServer(port: port);

/// Stop the agent server. Sync because stop() sends a oneshot and returns immediately.
void stopAgentServer() => RustLib.instance.api.crateApiAgentStopAgentServer();

/// Check if the agent server is currently running.
bool isAgentServerRunning() =>
    RustLib.instance.api.crateApiAgentIsAgentServerRunning();

/// Create a new API key with optional label. Returns the FULL token (shown once).
/// Caller MUST verify app password before calling this (auth challenge in Flutter).
Future<String> createApiKey({required String label}) =>
    RustLib.instance.api.crateApiAgentCreateApiKey(label: label);

/// Revoke an API key by its full token string.
/// Updates both disk config AND live server state.
/// Caller MUST verify app password before calling this.
Future<void> revokeApiKey({required String token}) =>
    RustLib.instance.api.crateApiAgentRevokeApiKey(token: token);

/// List all API keys as masked entries.
List<ApiKeyEntry> listApiKeys() =>
    RustLib.instance.api.crateApiAgentListApiKeys();

/// Get the full (unmasked) API key by its prefix. Used after auth challenge to reveal.
/// Caller MUST verify app password before calling this.
Future<String> getFullApiKey({required String tokenPrefix}) =>
    RustLib.instance.api.crateApiAgentGetFullApiKey(tokenPrefix: tokenPrefix);

/// Update the wallet data snapshot in the running server (called when Flutter refreshes data).
Future<void> updateAgentWalletData({
  double? solBalance,
  double? solUsd,
  required String tokensJson,
  required String historyJson,
  required String pricesJson,
}) => RustLib.instance.api.crateApiAgentUpdateAgentWalletData(
  solBalance: solBalance,
  solUsd: solUsd,
  tokensJson: tokensJson,
  historyJson: historyJson,
  pricesJson: pricesJson,
);

/// Stream new intents arriving at the agent server to Flutter.
/// Claims the intent receiver stored by start_agent_server.
/// Returns error if called before starting the server.
///
/// NOTE: Full implementation requires FRB codegen to implement SseEncode for IntentEvent.
/// The streaming loop body below is the intended implementation — enabled after codegen.
Stream<IntentEvent> streamIntents() =>
    RustLib.instance.api.crateApiAgentStreamIntents();

/// Approve a pending intent by ID.
Future<void> approveIntent({required String intentId}) =>
    RustLib.instance.api.crateApiAgentApproveIntent(intentId: intentId);

/// Reject a pending intent by ID.
Future<void> rejectIntent({required String intentId}) =>
    RustLib.instance.api.crateApiAgentRejectIntent(intentId: intentId);

/// Update an intent's status through the signing pipeline.
Future<void> updateIntentStatus({
  required String intentId,
  required String status,
  String? signature,
  String? error,
}) => RustLib.instance.api.crateApiAgentUpdateIntentStatus(
  intentId: intentId,
  status: status,
  signature: signature,
  error: error,
);

/// Server status event pushed to Flutter via StreamSink.
class AgentStatusEvent {
  final String status;
  final int? port;
  final String? error;

  const AgentStatusEvent({required this.status, this.port, this.error});

  @override
  int get hashCode => status.hashCode ^ port.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentStatusEvent &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          port == other.port &&
          error == other.error;
}

/// API key entry returned to Flutter (masked by default).
class ApiKeyEntry {
  final String tokenMasked;
  final String tokenPrefix;
  final String label;
  final PlatformInt64? createdAt;

  const ApiKeyEntry({
    required this.tokenMasked,
    required this.tokenPrefix,
    required this.label,
    this.createdAt,
  });

  @override
  int get hashCode =>
      tokenMasked.hashCode ^
      tokenPrefix.hashCode ^
      label.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiKeyEntry &&
          runtimeType == other.runtimeType &&
          tokenMasked == other.tokenMasked &&
          tokenPrefix == other.tokenPrefix &&
          label == other.label &&
          createdAt == other.createdAt;
}

/// Intent event pushed to Flutter via StreamSink.
class IntentEvent {
  final String id;
  final String intentTypeJson;
  final BigInt createdAt;
  final String apiTokenPrefix;

  const IntentEvent({
    required this.id,
    required this.intentTypeJson,
    required this.createdAt,
    required this.apiTokenPrefix,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      intentTypeJson.hashCode ^
      createdAt.hashCode ^
      apiTokenPrefix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntentEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          intentTypeJson == other.intentTypeJson &&
          createdAt == other.createdAt &&
          apiTokenPrefix == other.apiTokenPrefix;
}
