// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Set the app password (during onboarding). Async because scrypt is CPU-intensive.
Future<void> setAppPassword({required String password}) =>
    RustLib.instance.api.crateApiAuthSetAppPassword(password: password);

/// Verify the app password (for unlock). Async because scrypt is CPU-intensive.
Future<void> verifyAppPassword({required String password}) =>
    RustLib.instance.api.crateApiAuthVerifyAppPassword(password: password);

/// Change the app password. Requires current password verification first.
Future<void> changeAppPassword({
  required String current,
  required String newPassword,
}) => RustLib.instance.api.crateApiAuthChangeAppPassword(
  current: current,
  newPassword: newPassword,
);

/// Check if an app password has been set.
bool hasAppPassword() => RustLib.instance.api.crateApiAuthHasAppPassword();

/// Check if the app is currently locked.
bool isAppLocked() => RustLib.instance.api.crateApiAuthIsAppLocked();

/// Lock the app: set AtomicBool to true, then lock all wallets (zeroize seeds).
Future<void> lockApp() => RustLib.instance.api.crateApiAuthLockApp();

/// Unlock the app after password verification.
/// Caller must call verify_app_password first, then call this.
/// This unlocks all Keychain wallets into the session and sets AtomicBool to false.
Future<void> unlockApp() => RustLib.instance.api.crateApiAuthUnlockApp();
