// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get current guardrails config as a DTO.
/// Reads from the WalletManager singleton config.
GuardrailsConfigDto getGuardrailsConfig() =>
    RustLib.instance.api.crateApiGuardrailsGetGuardrailsConfig();

/// Update guardrails config. Persists to disk via AppConfig.save() and pushes to live server.
/// Called from Flutter when user changes master toggle or token whitelist.
Future<void> updateGuardrailsConfig({required GuardrailsConfigDto dto}) =>
    RustLib.instance.api.crateApiGuardrailsUpdateGuardrailsConfig(dto: dto);

/// Check a manual transaction (send or swap) against guardrails.
/// Called from Flutter review screen before signing.
/// mint: the SPL token mint for send_token (None for SOL sends).
/// output_mint: the swap output token mint (None for non-swap transactions).
/// Returns None if the transaction passes, Some(violation_message) if blocked.
String? checkManualTransaction({String? mint, String? outputMint}) =>
    RustLib.instance.api.crateApiGuardrailsCheckManualTransaction(
      mint: mint,
      outputMint: outputMint,
    );

/// DTO for passing guardrails config between Rust and Flutter.
/// Only includes fields relevant to v1 UI (enabled + token_whitelist).
class GuardrailsConfigDto {
  final bool enabled;
  final List<String> tokenWhitelist;

  const GuardrailsConfigDto({
    required this.enabled,
    required this.tokenWhitelist,
  });

  @override
  int get hashCode => enabled.hashCode ^ tokenWhitelist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuardrailsConfigDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          tokenWhitelist == other.tokenWhitelist;
}
