// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `read_json_line`, `send_command`

/// Scan serial ports for potential hardware wallets.
Future<List<DetectedPortDto>> scanHardwareWallets() =>
    RustLib.instance.api.crateApiHardwareScanHardwareWallets();

/// Connect to a hardware wallet, registering it in the config.
Future<WalletInfoDto> connectHardwareWallet({
  required String portPath,
  required String name,
}) => RustLib.instance.api.crateApiHardwareConnectHardwareWallet(
  portPath: portPath,
  name: name,
);

/// A detected serial port that may be an Unruggable hardware wallet.
class DetectedPortDto {
  final String path;
  final int vid;
  final int pid;
  final String product;

  const DetectedPortDto({
    required this.path,
    required this.vid,
    required this.pid,
    required this.product,
  });

  @override
  int get hashCode =>
      path.hashCode ^ vid.hashCode ^ pid.hashCode ^ product.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectedPortDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          vid == other.vid &&
          pid == other.pid &&
          product == other.product;
}
