// Hand-written stubs for hardware bridge functions added in Phase 05 Plan 02.
// These will be replaced by FRB codegen when the Rust bridge is regenerated.
// Do NOT add these to hardware.dart — that file is auto-generated by flutter_rust_bridge.

// ignore_for_file: unused_import

/// Read the public key stored on the connected hardware wallet.
/// Stub: replaced by FRB codegen when Rust bridge builds.
Future<String> getHardwarePubkey({required String portPath}) {
  throw UnimplementedError('getHardwarePubkey: awaiting FRB codegen');
}

/// Generate a new keypair on the hardware wallet (PBKDF2 + SLIP-0010).
/// Returns the 12 mnemonic words as a list.
/// Stub: replaced by FRB codegen when Rust bridge builds.
Future<List<String>> generateHardwareKeypair({required String portPath}) {
  throw UnimplementedError('generateHardwareKeypair: awaiting FRB codegen');
}

/// Erase the device private key and reset to factory state.
/// Stub: replaced by FRB codegen when Rust bridge builds.
Future<void> factoryResetHardware({required String portPath}) {
  throw UnimplementedError('factoryResetHardware: awaiting FRB codegen');
}

/// Verify that the hardware entropy source passes quality checks before generation.
/// Stub: replaced by FRB codegen when Rust bridge builds.
Future<void> checkHardwareEntropy({required String portPath}) {
  throw UnimplementedError('checkHardwareEntropy: awaiting FRB codegen');
}
