// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `esp32_signer`

/// Build and sign a SOL transfer transaction.
///
/// The active wallet must be unlocked first via `unlock_wallet`.
/// Returns the base64-encoded signed transaction and its signature.
Future<SignedTxDto> signSendSol({
  required String toAddress,
  required BigInt lamports,
  required String recentBlockhash,
  int? computeUnitLimit,
  BigInt? computeUnitPrice,
  BigInt? jitoTipLamports,
}) => RustLib.instance.api.crateApiSendSignSendSol(
  toAddress: toAddress,
  lamports: lamports,
  recentBlockhash: recentBlockhash,
  computeUnitLimit: computeUnitLimit,
  computeUnitPrice: computeUnitPrice,
  jitoTipLamports: jitoTipLamports,
);

/// Build and sign an SPL token transfer transaction.
///
/// The active wallet must be unlocked first via `unlock_wallet`.
/// ATAs are derived automatically. Set `create_ata_if_needed` to true
/// to include a CreateAssociatedTokenAccount instruction for the recipient.
Future<SignedTxDto> signSendToken({
  required String toAddress,
  required String mintAddress,
  required BigInt amount,
  required String recentBlockhash,
  required bool createAtaIfNeeded,
  int? computeUnitLimit,
  BigInt? computeUnitPrice,
  BigInt? jitoTipLamports,
}) => RustLib.instance.api.crateApiSendSignSendToken(
  toAddress: toAddress,
  mintAddress: mintAddress,
  amount: amount,
  recentBlockhash: recentBlockhash,
  createAtaIfNeeded: createAtaIfNeeded,
  computeUnitLimit: computeUnitLimit,
  computeUnitPrice: computeUnitPrice,
  jitoTipLamports: jitoTipLamports,
);

/// Build an unsigned SOL transfer transaction for simulation.
///
/// Uses the active wallet's public key as fee payer but does NOT sign.
/// The returned base64 has zeroed signatures — suitable for simulateTransaction
/// with sigVerify=false and replaceRecentBlockhash=true.
Future<String> buildUnsignedSendSol({
  required String toAddress,
  required BigInt lamports,
}) => RustLib.instance.api.crateApiSendBuildUnsignedSendSol(
  toAddress: toAddress,
  lamports: lamports,
);

/// Build an unsigned SPL token transfer transaction for simulation.
///
/// Uses the active wallet's public key as fee payer but does NOT sign.
/// The returned base64 has zeroed signatures — suitable for simulateTransaction
/// with sigVerify=false and replaceRecentBlockhash=true.
Future<String> buildUnsignedSendToken({
  required String toAddress,
  required String mintAddress,
  required BigInt amount,
  required bool createAtaIfNeeded,
}) => RustLib.instance.api.crateApiSendBuildUnsignedSendToken(
  toAddress: toAddress,
  mintAddress: mintAddress,
  amount: amount,
  createAtaIfNeeded: createAtaIfNeeded,
);

/// Build and sign a SOL transfer via an ESP32 hardware wallet.
///
/// Connects to the ESP32 at `port_path`, builds the transaction, then the
/// device LED pulses and the user must press BOOT within 30 seconds.
Future<SignedTxDto> signSendSolHardware({
  required String portPath,
  required String toAddress,
  required BigInt lamports,
  required String recentBlockhash,
  int? computeUnitLimit,
  BigInt? computeUnitPrice,
  BigInt? jitoTipLamports,
}) => RustLib.instance.api.crateApiSendSignSendSolHardware(
  portPath: portPath,
  toAddress: toAddress,
  lamports: lamports,
  recentBlockhash: recentBlockhash,
  computeUnitLimit: computeUnitLimit,
  computeUnitPrice: computeUnitPrice,
  jitoTipLamports: jitoTipLamports,
);

/// Build and sign an SPL token transfer via an ESP32 hardware wallet.
Future<SignedTxDto> signSendTokenHardware({
  required String portPath,
  required String toAddress,
  required String mintAddress,
  required BigInt amount,
  required String recentBlockhash,
  required bool createAtaIfNeeded,
  int? computeUnitLimit,
  BigInt? computeUnitPrice,
  BigInt? jitoTipLamports,
}) => RustLib.instance.api.crateApiSendSignSendTokenHardware(
  portPath: portPath,
  toAddress: toAddress,
  mintAddress: mintAddress,
  amount: amount,
  recentBlockhash: recentBlockhash,
  createAtaIfNeeded: createAtaIfNeeded,
  computeUnitLimit: computeUnitLimit,
  computeUnitPrice: computeUnitPrice,
  jitoTipLamports: jitoTipLamports,
);
