// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `sign_tx_with`

/// Sign a pre-built serialized transaction (base64-encoded).
///
/// Takes an unsigned (or partially-signed) VersionedTransaction from an
/// external source (Jupiter, DFlow, Sanctum, etc.), signs it with the
/// active wallet's keypair, and returns the signed base64 + first signature.
Future<SignedTxDto> signSerializedTransaction({
  required String unsignedTxBase64,
}) => RustLib.instance.api.crateApiSignSignSerializedTransaction(
  unsignedTxBase64: unsignedTxBase64,
);

/// Sign a pre-built serialized transaction via an ESP32 hardware wallet.
Future<SignedTxDto> signSerializedTransactionHardware({
  required String portPath,
  required String unsignedTxBase64,
}) => RustLib.instance.api.crateApiSignSignSerializedTransactionHardware(
  portPath: portPath,
  unsignedTxBase64: unsignedTxBase64,
);
