// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_core`

/// Result of creating a new wallet.
class CreateWalletResult {
  final WalletInfoDto wallet;
  final List<String> mnemonicWords;

  const CreateWalletResult({required this.wallet, required this.mnemonicWords});

  @override
  int get hashCode => wallet.hashCode ^ mnemonicWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateWalletResult &&
          runtimeType == other.runtimeType &&
          wallet == other.wallet &&
          mnemonicWords == other.mnemonicWords;
}

/// Result of building and signing a transaction (for Dart).
class SignedTxDto {
  /// Base64-encoded signed transaction, ready for RPC submission.
  final String base64;

  /// Transaction signature (hex-encoded).
  final String signature;

  const SignedTxDto({required this.base64, required this.signature});

  @override
  int get hashCode => base64.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedTxDto &&
          runtimeType == other.runtimeType &&
          base64 == other.base64 &&
          signature == other.signature;
}

/// Flattened wallet info for Dart consumption.
class WalletInfoDto {
  final String address;
  final String name;
  final String source;

  const WalletInfoDto({
    required this.address,
    required this.name,
    required this.source,
  });

  @override
  int get hashCode => address.hashCode ^ name.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletInfoDto &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          name == other.name &&
          source == other.source;
}
