// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `manager`, `storage`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `manager_pub`

/// Create a new wallet from a generated mnemonic.
Future<CreateWalletResult> createWallet({
  required String name,
  required int wordCount,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  name: name,
  wordCount: wordCount,
);

/// Import a wallet from a mnemonic phrase.
Future<WalletInfoDto> importWallet({
  required String name,
  required List<String> words,
}) => RustLib.instance.api.crateApiWalletImportWallet(name: name, words: words);

/// List all wallets.
Future<List<WalletInfoDto>> listWallets() =>
    RustLib.instance.api.crateApiWalletListWallets();

/// Set the active wallet by address.
Future<void> setActiveWallet({required String address}) =>
    RustLib.instance.api.crateApiWalletSetActiveWallet(address: address);

/// Get the active wallet address.
String? getActiveWallet() =>
    RustLib.instance.api.crateApiWalletGetActiveWallet();

/// Remove a wallet by address.
Future<void> removeWallet({required String address}) =>
    RustLib.instance.api.crateApiWalletRemoveWallet(address: address);

/// Unlock a wallet (loads seed into memory session).
Future<void> unlockWallet({required String address}) =>
    RustLib.instance.api.crateApiWalletUnlockWallet(address: address);

/// Lock a wallet (zeroizes seed from memory).
Future<void> lockWallet({required String address}) =>
    RustLib.instance.api.crateApiWalletLockWallet(address: address);

/// Lock all wallets.
Future<void> lockAllWallets() =>
    RustLib.instance.api.crateApiWalletLockAllWallets();

/// Check if a wallet is unlocked.
bool isWalletUnlocked({required String address}) =>
    RustLib.instance.api.crateApiWalletIsWalletUnlocked(address: address);

/// Retrieve the mnemonic for a wallet.
Future<List<String>> getMnemonic({required String address}) =>
    RustLib.instance.api.crateApiWalletGetMnemonic(address: address);

/// Check if the user needs to go through onboarding.
bool needsOnboarding() => RustLib.instance.api.crateApiWalletNeedsOnboarding();

/// Mark onboarding as completed.
Future<void> completeOnboarding() =>
    RustLib.instance.api.crateApiWalletCompleteOnboarding();

/// Validate a mnemonic phrase (for import flow).
bool validateMnemonic({required List<String> words}) =>
    RustLib.instance.api.crateApiWalletValidateMnemonic(words: words);

/// Pick N random BIP39 words (for quiz distractors).
List<String> randomBip39Words({required int count}) =>
    RustLib.instance.api.crateApiWalletRandomBip39Words(count: count);

/// Reset onboarding flag (debug/settings use).
Future<void> resetOnboarding() =>
    RustLib.instance.api.crateApiWalletResetOnboarding();

/// Get the current network setting.
String getNetwork() => RustLib.instance.api.crateApiWalletGetNetwork();

/// Set the network (e.g. "mainnet", "devnet", "testnet").
Future<void> setNetwork({required String network}) =>
    RustLib.instance.api.crateApiWalletSetNetwork(network: network);

/// Get the Helius API key.
String getHeliusApiKey() =>
    RustLib.instance.api.crateApiWalletGetHeliusApiKey();

/// Set the Helius API key.
Future<void> setHeliusApiKey({required String key}) =>
    RustLib.instance.api.crateApiWalletSetHeliusApiKey(key: key);
